name: codesign
channels:
  - conda-forge
dependencies:
  # --- Core ---
  - python=3.11
  - pip
  - libblas=*=*openblas          # switch to =*mkl if you prefer MKL
  - numpy>=1.26,<2
  - scipy>=1.11,<2
  - pandas>=2.2
  - matplotlib>=3.8
  - seaborn>=0.13
  - ipython>=8.20
  - ipykernel>=6.25
  - jupyter_client>=8.6
  - jupyter_core>=5.5
  - python-dateutil
  - pytz
  - tzdata
  - pyparsing
  - pyyaml
  - setuptools
  - wheel

  # --- Optimization / Modeling ---
  - cvxpy=1.5.*
  - clarabel>=0.7
  - ipopt=3.14.*
  - pyomo=6.7.*
  - ampl-mp=3.1.0

  # --- Graph / Viz toolchain ---
  - graphviz
  - python-graphviz
  - pygraphviz>=1.9

  # --- EDA / Build toolchain ---
  - yosys
  - gcc_linux-64=13
  - gxx_linux-64=13
  - autoconf
  - automake
  - libtool
  - gperf
  - flex
  - bison
  - perl
  - make
  - git
  - help2man

  # --- ML stacks ---
  - pytorch=2.1.*                # CPU build; add CUDA toolkit if needed
  - jax=0.4.28
  - jaxlib=0.4.28
  - equinox=0.11.4
  - jaxtyping=0.2.29
  - opt-einsum=3.3.0
  - typeguard=2.13.3
  - pytest                       # loosened (was 8.3.0)

  # --- pip-only bits ---
  - pip:
      - ml-dtypes==0.4.0         # pip-only
      - sympy2jax==0.0.5
      - astpretty==3.0.0

