name: Debug Latest Workflow

on:
  workflow_dispatch:  
  push:               
    branches:
      - eric/latest
      - main

jobs:
  test:
    runs-on: codesign-test-2
    steps:
      - name: Remove old workspace
        run: |
          rm -rf *
          rm -rf .[^.] .??*
    
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
          clean: true

      - name: Debug-echo
        run: |
          echo ">>> CI is running inside Python Tests workflow on $(date)"
          echo "Current directory: $(pwd)"
          ls -la
        
      - name: Set up bash and run environment setup
        env:
          SUDO_PASSWORD: ${{ secrets.SUDO_PASSWORD }}
        run: |
          source ./full_env_start.sh

      - name: Run custom script
        run: |
          chmod +x scripts-ci_temp.sh || true
          ./scripts-ci_temp.sh
