name: Python Tests

on:
   pull_request:

jobs:
  test:
    runs-on: codesign-runner-test
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Run custom script
        run: |
          chmod +x scripts/scripts-ci.sh || true
          ./scripts/scripts-ci.sh
